import UIKit

@UIApplicationMain class AppDelegate: UIResponder, UIApplicationDelegate {
    var window: UIWindow?
    
    let r = Aver<String>()
    
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        
        generateReadme()
        
        return true
    }
    
    func generateDiff() -> Tree<Element<String>> {
        
        return .doc() -- [
            .header("diffing", level: 2)-,
            .text("were gonna talk about diffing")-
        ]
    }
    
    func generateReadme() {
        
        let treeText =
        """
            .doc() -- [
                .blockQuoted() -- [
                    .text("NOTE: this ReadMe is generated by Aver itself.")-,
                    .text("The rendering code is the following: ")-
                ],
                .codeBlock() -- [
                    .text(treeText)-
                ],
                .header("Aver")-,
                .divider()-,
                .text("topics")-,
                .list() -- [
                    .text("diffing")-,
                    .text("resolving")-,
                    .text("rendering")-,
                ]
            ]
        """
        
        
        let tr: Tree<Element<String>> = .doc() -- [
            .blockQuoted() -- [
                .text("NOTE: this ReadMe is generated by Aver itself.")-,
                .newLine()-,
                .text("The rendering code is the following: ")-
            ],
            .codeBlock() -- [
                .text(treeText)-
            ],
            .header("Aver", level: 3)-,
            .divider()-,
            .text("topics")-,
            .list() -- [
                .text("diffing")-,
                .text("resolving")-,
                .text("rendering")-,
            ],
            .horizontal()-,
            .newLine()-,
            generateDiff()
            
        ]
        
        let result = r.render(tr)
        
        print(result)
        
    }
}
